services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=reservas_vehiculos.settings
      - POSTGRES_DB=reservas_vehiculos
      - POSTGRES_USER=nuevo_usuario
      - POSTGRES_PASSWORD=contraseña1
      - DB_HOST=db
      - DB_PORT=5432
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: reservas_vehiculos
      POSTGRES_USER: nuevo_usuario
      POSTGRES_PASSWORD: contraseña1
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

volumes:
  db_data: