# Generated by Django 5.2 on 2025-05-05 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('license_plate', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(choices=[('CAR', 'automobile'), ('VAN', 'van'), ('MOTORBIKE', 'Motorbike'), ('BUS', 'bus')], max_length=10)),
                ('condition', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'In maintenance'), ('OUT_OF_SERVICE', 'Out of service')], default='AVAILABLE', max_length=20)),
                ('mileage', models.PositiveIntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.color')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.vehiclemodel')),
            ],
        ),
    ]
