# cloudbuild.yaml (En la raíz del repositorio, fuera de la carpeta 'reservas_vehiculos')
steps:
  # =================================================================
  # 1. CUSTOMERS - BUILD & PUSH
  # =================================================================
  - name: gcr.io/cloud-builders/docker
    id: Build Customers Image
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/practica2-477009/reservas-vehiculo/customers-service",
        "." # Contexto: la carpeta actual (reservas_vehiculos/customers/)
      ]
    # ¡LA CORRECCIÓN! El directorio es relativo a la raíz del repositorio
    dir: reservas_vehiculos/customers
  
  - name: gcr.io/cloud-builders/docker
    id: Push Customers Image
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/practica2-477009/reservas-vehiculo/customers-service"
      ]

  # =================================================================
  # 2. CUSTOMERS - DEPLOY (Usando service.yaml)
  # =================================================================
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy Customers Service (YAML)
    # Nos movemos a la carpeta que contiene el service.yaml
    dir: reservas_vehiculos/customers 
    entrypoint: gcloud
    args:
      [
        "run", "services", "replace", "service.yaml",
        "--region=us-central1",
        "--platform=managed",
        "--project=practica2-477009",
      ]
    
  # =================================================================
  # PASO 3: CONFIGURAR ACCESO PÚBLICO (IAM)
  # =================================================================
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Set Public Access
    entrypoint: gcloud
    args:
      [
        "run", "services", "add-iam-policy-binding", "customers-service",
        "--member=allUsers",
        "--role=roles/run.invoker",
        "--region=us-central1",
        "--platform=managed"
      ]

  # (Continúa con los demás microservicios: employees, vehicles, etc., usando la misma lógica de 'dir:')

images:
  - "us-central1-docker.pkg.dev/practica2-477009/reservas-vehiculo/customers-service"
  
options:
  logging: CLOUD_LOGGING_ONLY