steps:
  # =================================================================
  # 1. CUSTOMERS - BUILD & PUSH (SOLUCIÓN DEFINITIVA DE PATHS)
  # =================================================================
  - name: gcr.io/cloud-builders/docker
    id: Build Customers Image
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/practica2-477009/reservas-vehiculo/customers-service",
        # Ruta COMPLETA desde la raíz del repositorio para el Dockerfile:
        "-f", "reservas_vehiculos/customers/Dockerfile", 
        "." # Contexto: La raíz del repositorio.
      ]
    # Se ELIMINA 'dir' para este paso.
  
  - name: gcr.io/cloud-builders/docker
    id: Push Customers Image
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/practica2-477009/reservas-vehiculo/customers-service"
      ]

  # =================================================================
  # 2. CUSTOMERS - DEPLOY (Usando service.yaml)
  # =================================================================
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy Customers Service (YAML)
    # Ruta donde se encuentra el service.yaml
    dir: reservas_vehiculos/customers 
    entrypoint: gcloud
    args:
      [
        "run", "services", "replace", "service.yaml",
        "--region=us-central1",
        "--platform=managed",
        "--project=practica2-477009",
      ]
    
  # =================================================================
  # PASO 3: CONFIGURAR ACCESO PÚBLICO (IAM)
  # =================================================================
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Set Public Access
    entrypoint: gcloud
    args:
      [
        "run", "services", "add-iam-policy-binding", "customers-service",
        "--member=allUsers",
        "--role=roles/run.invoker",
        "--region=us-central1",
        "--platform=managed"
      ]
# ... (El resto del YAML)
images:
  - "us-central1-docker.pkg.dev/practica2-477009/reservas-vehiculo/customers-service"
  
options:
  logging: CLOUD_LOGGING_ONLY